version: '2' 
services:
  nginx:
    build: nginx-image
    mem_limit: 2g
    cpu_shares: 256
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes_from:
      - letsencrypt
    networks:
      - boutique
  letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
#    command:  bash -c "sleep 6 && certbot certonly --standalone -d mortonprod.co.uk --text --agree-tos --email mortonprod@gmail.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
    command: bash /start.sh
    entrypoint: ""
    volumes:
      - /etc/letsencrypt
      - /var/lib/letsencrypt
      - ./start.sh:/start.sh
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm
networks:
  boutique:
    external: 
      name: boutiquebackendv2_default


